# 项目相关配置
dawn:
  # 名称
  name: Dawn
  # 描述
  description: 分布式数据库管理系统
  # 版本
  version: 1.0.0
  # 获取ip地址开关
  addressEnabled: true
  #演示模式
  demoMode: false
  # 实例演示开关
  demoEnabled: true
  # 文件上传路径
  profile: D:/profile/

  user:
    indexUrl: /index

#logging

# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 500
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

## 日志配置
#logging:
#  config: classpath:logConfig/log4j2.xml
#  level:
#    com.neutrino.dawn: debug
#    org.springframework: warn

# 日志配置
logging:
  level:
    com.neutrino.dawn: debug
    org.springframework: warn


# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

  # 数据源配置
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      platform: mysql
      url: jdbc:mysql://192.168.137.137:3306/dawn
      username: mysql
      password: mysql_2019!
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /monitor/druid/*

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.neutrino
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml
